#!/bin/bash

CURRDIR=`pwd`
INSTDIR=r'/usr/bin/'
CALIGNDIR='/cygdrive/c/User/chain/Download/CALIGN/'

chmod a+x *.sh *.py
SHFILE=`ls *.sh *.py`

for f in $SHFILE;
do
    echo "Installing $f..."
    ln -s $CURRDIR/$f $INSTDIR/$f
done
